import 'package:lost_ark_buddy/gear.dart';
import 'package:lost_ark_buddy/honing_material.dart';

Gear weapon21 = Gear(
  tier: Tier.ancient,
  type: Type.weapon,
  iLevel: 1630,
  requiredXp: 150000,
  feedSilver: 2250000,
  basicSuccessRate: .03,
  crystalsPerHone: 1350,
  leapstonesPerHone: 33,
  fusionMaterialsPerHone: 30,
  shardsPerHone: 15000,
  goldPerHone: 2350,
  silverPerHone: 55000,
  crystals: protectionStone,
  leapstones: marvelousLeapstone,
  fusionMaterials: superiorOrehaFusionMaterial,
  shards: honorShards,
);

Gear weapon22 = Gear(
  tier: Tier.ancient,
  type: Type.weapon,
  iLevel: 1635,
  requiredXp: 180000,
  feedSilver: 2340000,
  basicSuccessRate: .02,
  crystalsPerHone: 1450,
  leapstonesPerHone: 36,
  fusionMaterialsPerHone: 30,
  shardsPerHone: 15000,
  goldPerHone: 2600,
  silverPerHone: 55000,
  crystals: obliterationStone,
  leapstones: marvelousLeapstone,
  fusionMaterials: superiorOrehaFusionMaterial,
  shards: honorShards,
);

Gear weapon23 = Gear(
  tier: Tier.ancient,
  type: Type.weapon,
  iLevel: 1640,
  requiredXp: 21000,
  feedSilver: 2520000,
  basicSuccessRate: .02,
  crystalsPerHone: 1600,
  leapstonesPerHone: 40,
  fusionMaterialsPerHone: 30,
  shardsPerHone: 17000,
  goldPerHone: 2910,
  silverPerHone: 55000,
  crystals: obliterationStone,
  leapstones: marvelousLeapstone,
  fusionMaterials: superiorOrehaFusionMaterial,
  shards: honorShards,
);

Gear weapon24 = Gear(
  tier: Tier.ancient,
  type: Type.weapon,
  iLevel: 1645,
  requiredXp: 250000,
  feedSilver: 2750000,
  basicSuccessRate: .015,
  crystalsPerHone: 1850,
  leapstonesPerHone: 44,
  fusionMaterialsPerHone: 45,
  shardsPerHone: 19000,
  goldPerHone: 3290,
  silverPerHone: 55000,
  crystals: obliterationStone,
  leapstones: marvelousLeapstone,
  fusionMaterials: superiorOrehaFusionMaterial,
  shards: honorShards,
);

Gear weapon25 = Gear(
  tier: Tier.ancient,
  type: Type.weapon,
  iLevel: 1650,
  requiredXp: 300000,
  feedSilver: 4500000,
  basicSuccessRate: .015,
  crystalsPerHone: 2150,
  leapstonesPerHone: 48,
  fusionMaterialsPerHone: 45,
  shardsPerHone: 22000,
  goldPerHone: 3750,
  silverPerHone: 55000,
  crystals: obliterationStone,
  leapstones: marvelousLeapstone,
  fusionMaterials: superiorOrehaFusionMaterial,
  shards: honorShards,
);
